connoisseur/config/routes.rb
Connoisseur::Application.routes.draw do
  resources :stores
  resources :products

end

connoisseur/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

connoisseur/app/controllers/products_controller.rb
require 'json'
require 'open-uri'

class ProductsController < ApplicationController
  
  def index
      products_json = open('http://lcboapi.com/products?per_page=30').read
      @products = JSON.parse(products_json)
  end

  def show
      products_json = open("http://lcboapi.com/products/#{params[:id]}").read        
      @products = JSON.parse(products_json)
  end

end

connoisseur/app/controllers/stores_controller.rb
require 'json'
require 'open-uri'

class StoresController < ApplicationController
  def index
      stores_json = open('http://lcboapi.com/stores?per_page=30').read
      @stores = JSON.parse(stores_json)
  end

  def show
  	  stores_json = open("http://lcboapi.com/stores/#{params[:id]}").read        
      @stores = JSON.parse(stores_json)
  end
end

connoisseur/app/helpers/application_helper.rb
module ApplicationHelper
end

connoisseur/app/helpers/products_helper.rb
module ProductsHelper
end

connoisseur/app/helpers/stores_helper.rb
module StoresHelper
end

connoisseur/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connoisseur</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

connoisseur/app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

connoisseur/app/views/products/index.html.erb
<h1>Alcohol</h1>

<% @products['result'].each do |product| %>
  	<section>
   		<p> <%= link_to product['name'], product_path(product['id']) %></p>
    	<p>Price: <%=  number_to_currency(product['price_in_cents'].to_f / 100 ) %></p>
    	<p><%= product['primary_category'] %></p>
  	</section>
<% end %>
<br>
<h2><%= link_to 'Stores', "stores#index" %></h2>

connoisseur/app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

connoisseur/app/views/products/show.html.erb
<h4><%= link_to 'Back', products_url %></h4>

<% products = @products['result'] %>

<h3>Brand: <%= products['name'] %></h3>
<p>Price: <%= number_to_currency(products['price_in_cents'].to_f / 100 ) %></p>
<p>Category: <%= products['primary_category'] %></p>
<p>Inventory Count: <%= products['inventory_count']  %></p>

connoisseur/app/views/stores/index.html.erb
<h1>Stores</h1>

<% @stores['result'].each do |store| %>
	<section>
		<p><%= link_to store['name'], store_path(store['id']) %></p>
	</section>
<% end %>
<br>
<h2><%= link_to 'Alcohol', 'products#index' %></h2>

connoisseur/app/views/stores/show.html.erb
<h4><%= link_to 'Back', stores_url %></h4>
<% stores = @stores['result'] %>

<h2>Store: <%= stores['name'] %></h2>

<p><%= stores['city'] %></p> 
<p>Address:  <%= stores['address_line_1'] %>, <%= stores['address_line_2']%></p>
<p><%= stores ['postal_code'] %></p>

<h4>Tel: <%= stores['telephone'] %></h4>

<h3>Store Hours</h3>
<p>Sunday: <%= stores['sunday_open'] %> - <%= stores['sunday_close']%></p>
<p>Monday: <%= stores['monday_open'] %> - <%= stores['monday_close']%></p>
<p>Tuesday: <%= stores['tuesday_open'] %> - <%= stores['tuesday_close']%></p>
<p>Wednesday: <%= stores['wednesday_open'] %> - <%= stores['wednesday_close']%></p>
<p>Thursday: <%= stores['thursday_open'] %> - <%= stores['thursday_close']%></p>
<p>Friday: <%= stores['friday_open'] %> - <%= stores['friday_close']%></p>
<p>Saturday: <%= stores['saturday_open'] %> - <%= stores['saturday_close']%></p>